spring.application.name=complaint_service
server.port=8085


spring.datasource.url=jdbc:postgresql://localhost:5433/complaint_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

room.service.url=http://localhost:8082
tenant.service.url=http://localhost:8083
payments.service.url=http://localhost:8084

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

smtp.host=smtp.gmail.com
smtp.port=587

jwt.secret=${JWT_SECRET}

jwt.expiration=900000

# 15 menit
# 900000 ms

jwt.refresh-expiration=180

# 7 hari

logging.level.org.springframework.security=DEBUG