spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.routes[0].id=auth
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[0].filters[0]=JwtAuthenticationFilter
spring.cloud.gateway.routes[0].order=1

spring.cloud.gateway.routes[1].id=room
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/rooms/**
spring.cloud.gateway.routes[1].filters[0]=JwtAuthenticationFilter
spring.cloud.gateway.routes[1].order=1

spring.cloud.gateway.routes[2].id=tenant
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/tenants/**
spring.cloud.gateway.routes[2].filters[0]=JwtAuthenticationFilter
spring.cloud.gateway.routes[2].order=1

spring.cloud.gateway.routes[3].id=payment
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/payments/**
spring.cloud.gateway.routes[3].filters[0]=JwtAuthenticationFilter
spring.cloud.gateway.routes[3].order=1

spring.cloud.gateway.routes[4].id=complaint
spring.cloud.gateway.routes[4].uri=http://localhost:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/complaints/**
spring.cloud.gateway.routes[4].filters[0]=JwtAuthenticationFilter
spring.cloud.gateway.routes[4].order=1

spring.cloud.gateway.routes[5].id=smartkost
spring.cloud.gateway.routes[5].uri=http://localhost:8090
spring.cloud.gateway.routes[5].predicates[0]=Path=/**
spring.cloud.gateway.routes[5].filters[0]=JwtAuthenticationFilter
spring.cloud.gateway.routes[5].order=100

spring.cloud.gateway.routes[6].id=room-uploads
spring.cloud.gateway.routes[6].uri=http://localhost:8082
spring.cloud.gateway.routes[6].predicates[0]=Path=/uploads/rooms/**
spring.cloud.gateway.routes[6].order=0

spring.cloud.gateway.routes[7].id=payment-uploads
spring.cloud.gateway.routes[7].uri=http://localhost:8084
spring.cloud.gateway.routes[7].predicates[0]=Path=/uploads/payments/**
spring.cloud.gateway.routes[7].order=0

logging.level.org.springframework.cloud.gateway=DEBUG
jwt.secret=${JWT_SECRET}

spring.codec.max-in-memory-size=10MB