spring.application.name=auth
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/auth_db
spring.datasource.username=postgres
spring.datasource.password=mut123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

smtp.host=smtp.gmail.com
smtp.port=587

jwt.secret=MySuperSecretKeyForSmartKostAuthService2026

jwt.expiration=900000

# 15 menit
# 900000 ms

jwt.refresh-expiration=180

# 7 hari
# 604800000 ms

# ==========================
# SWAGGER
# ==========================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ==========================
# LOGGING
# ==========================
logging.level.org.springframework.security=DEBUG

