spring.application.name=payment_service
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5433/payment_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

room.service.url=http://localhost:8082
tenant.service.url=http://localhost:8083

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=tiaqizdokumen@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=${JWT_SECRET}
jwt.expiration=900000
jwt.refresh-expiration=180

app.base-url=http://192.168.43.151:8080

# ==========================
# LOGGING
# ==========================
logging.level.org.springframework.security=DEBUG

# Multipart size
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB