spring.application.name=tenant_service
server.port=8083

# Database
spring.datasource.url=jdbc:postgresql://localhost:5433/tenant_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Room Service URL
room.service.url=http://localhost:8082

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=900000
jwt.refresh-expiration=604800000

# ==========================
# LOGGING
# ==========================
logging.level.org.springframework.security=DEBUG
